### ISSUE TITLE
Italic does not get displayed as italic on NC 25.

### ISSUE THREAD

**Issue by RobertZenz** [mamatt/files_readmemd#107]
Assuming you have the following file:

```markdown
This *should be italic*.
```

The "should be italic" should be italic, but instead the following style from the main NC styles get applied:

```css
/* apps.scss */
em {
  font-style: normal;
  color: var(--color-text-lighter);
}
```

Is that intentional?
